services:
  backend:
    build: .
    container_name: edutracker_backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./fake_remote:/app/fake_remote

    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: edutracker_frontend

    ports:
      - "3000:80"

    restart: unless-stopped
